config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  resources :profiles
  resources :posts
  get 'sessions/new'
  resources :users
  resources :favorites, only: [:create, :destroy, :index]
  resources :sessions, only: [:new, :create, :destroy]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
  validates :image, presence:true
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to posts_path, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to posts_path, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_profile
  @profile = Profile.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def profile_params
  params.require(:profile).permit(:image, :user_id, :image_cache)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
<% if profile.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>
    <ul>
    <% profile.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<div class="field">
  Choose an image: <%= form.file_field :image %>
</div>
<div class="field">
  <% if logged_in? %>
    <%= form.hidden_field :user_id, value: current_user.id%>
  <% end %>
</div>
<div class="actions">
  <%= form.submit class:"btn btn-primary new-form" %>
</div>
<% end %>

app/views/profiles/edit.html.erb
<div class="container new-prof-form">
  <h3>Editing Profile</h3>
  <%= render 'form', profile: @profile %>
  <%= link_to 'Show', @profile %> |
  <%= link_to 'Back', profiles_path %>
</div>

app/views/profiles/index.html.erb
<div class="container profile-all">
  <p id="notice"><%= notice %></p>
  <h3>Profiles</h3>
  <% @profiles.each do |profile| %>
    <div class="card all-profile">
      <div class="card-body">
        <div><%= image_tag profile.image.url, size:"350x200" %></div>
        <div><%= profile.user.name %></div>
      </div>
      <div class="footer">
        <%= link_to 'Show', profile %>
        <%= link_to 'Edit', edit_profile_path(profile) %>
        <%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %>   
      </div>
    </div>
  <% end %>
</div>

app/views/profiles/new.html.erb
<div class="container new-prof-form">
  <h5>New Profile</h5>
  <%= render 'form', profile: @profile %>
  <%= link_to 'Back', profiles_path %>
</div>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container show-profile">
  <div class="card">
    <div class="card-body">
      <%= image_tag @profile.image.url, size:"50x50" %>
      <%= @profile.user.name %>
    </div>
    <div class="card-footer">
      <%= link_to 'Edit', edit_profile_path(@profile) %> |
      <%= link_to 'Back', profiles_path %>
      </div>    
  </div>
</div>