config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  resources :profiles
  resources :posts
  get 'sessions/new'
  resources :users
  resources :favorites, only: [:create, :destroy, :index]
  resources :sessions, only: [:new, :create, :destroy]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, presence: true, length: {maximum: 30}
  validates :email, presence: true,
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }, uniqueness: true, length: {maximum: 255}
  before_validation { email.downcase! }
  has_many :posts
  has_one :profile
  has_many :favorites, dependent: :destroy
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to new_session_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user
  @user = User.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
  params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<div class="container">
  <div class="card login-fm" >
  <h1 class="instagram-title">New User</h1>
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group login-btn">
    <%= form.label :email %>
    <%= form.text_field :email, class:"form-control", placeholder:"Enter your email" %>
  </div>

  <div class="form-group login-btn">
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control", placeholder:"Enter name" %>
  </div>

  <div class="form-group login-btn">
    <%= form.label :password %>
    <%= form.password_field :password, class:"form-control", placeholder:"Enter password" %>
  </div>

  <div class="form-group login-btn">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class:"form-control", placeholder:"Re-enter your password" %>
  </div>

  <div class="login-btn">
    <%= form.submit class:"btn btn-primary btn-form"%>
  </div>
  
<% end %>
<div class="card second-card">
      <span id="sign-up">Have an account? <%= link_to "Login", new_session_path %></span>
</div>
</div>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<div class="container my-container">
  <p id="notice"><%= notice %></p>
  <h1>All Users</h1>
  <table class="table table-hover" style="width:50%">
    <thead>
      <tr>
        <th>Email</th>
        <th>Name</th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.email %></td>
          <td><%= user.name %></td>
          <td><%= link_to 'Show', user %></td>
          <%if logged_in? %>
          <% if current_user.id == user.id%>
          <td><%= link_to 'Edit', edit_user_path(user) %></td>
          <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <%end%>
          <%end%>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
</div>

app/views/users/new.html.erb
<div class="new-user-form">
    <%= render 'form', user: @user %>
</div>

app/views/users/show.html.erb
<div class="container show-page">
  <div class="card">
    <p id="notice"><%= notice %></p>
    <div class="card-body row">  
    <% if @user.profile.present? %> 
      <%= image_tag @user.profile.image.url,class:"rounded-circle", style:"margin-left: 50px; margin-right: 150px;", size:"150x150" unless @user.profile.image.url.blank? %>
      <% end %>
      <div class="user-name">     
      <%= @user.name %>
      </div>
      <%= link_to 'Edit Profile', edit_user_path(@user), class:"btn btn-default btn-warning profile-edit-btn" %>
     <!-- Example single danger button -->
  <div>
    <div class="btn-group">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <%= image_tag 'Settings.png', class:"btn-setting"%>
    </button>
    <div class="dropdown-menu">
    <div><%= link_to "Profile", user_path(current_user.id) %></div>
    <div><%= link_to "Logout", session_path(current_user.id), method: :delete %></div>
  </div>
</div>
  </div>
  </div> 
  </div>
</div>