config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  resources :profiles
  resources :posts
  get 'sessions/new'
  resources :users
  resources :favorites, only: [:create, :destroy, :index]
  resources :sessions, only: [:new, :create, :destroy]
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImageUploader
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @profiles=Profile.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
     @favorite = current_user.favorites.find_by(post_id: @post.id)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        # ContactMailer.contact_mail(@post).deliver 
        format.html { redirect_to posts_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
  @post = Post.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
  params.require(:post).permit(:blog, :image, :user_id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% if logged_in? %>
  <%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :Post %>
    <%= form.text_area :blog, class:"form-control" %>
  </div>

  <div class="form-group">
    Choose Image : <%= form.file_field :image, class:"post-content" %>
  </div>

  <div class="field">
    <% if logged_in? %>
    <%= form.hidden_field :user_id, value: current_user.id %>
    <%end%>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>
<%end%>

app/views/posts/edit.html.erb
<div class="container">
  <h1>Editing Post</h1>
  <%= render 'form', post: @post %>
  <%= link_to 'Show', @post %> |
  <%= link_to 'Back', posts_path %>   
<div>

app/views/posts/index.html.erb
<div class="container profile-pic"> 
  <div class="row">
    <div class="col-6">
      <p id="notice"><%= notice %></p>
      <% if logged_in? %>
      <% check = 0, links='1', id=nil, nam=nil %>
      <% @profiles.each do |profile| %>
        <% if current_user.id == profile.user_id %>
          <% check = 1%>
          <%links = profile.image.url %>
          <%id =profile%>
        <%nam= profile.user.name%>
        <% end %>
      <% end %>
      <% if check==1 %>
      <p><%= image_tag links, size:"150x150",class:"rounded-circle" unless links.blank? %></p>
      <p><%= nam%></p>
      <%= link_to 'Edit', edit_profile_path(id) %>
      <%= link_to 'Destroy', id, method: :delete, data: { confirm: 'Are you sure?' } %>

      <% else %>
      <p><%=image_tag "userImage.png"%></p>
      <%= nam%>
      <%= link_to 'Upload a profile picture', new_profile_path %>
      <% end %>
      <% end %>

      <div class="index-post">
        <h1>Posts</h1>
        <%= link_to 'New Post', new_post_path, class:"btn btn-primary" %>
        <br>
        <% @posts.each do |post| %>
          <div class="card my-card">
            <div class="card-body">
              <div><%= post.blog %></div>
              <div><%= image_tag post.image.url, alt:"No image posted",size: "450x350" unless post.image.url.blank? %></div>
              <div>Tagged By: <%= post.user.name %></div>
            </div>
            <div class="card-footer">
            <%= link_to 'Show', post, class:"btn btn-secondary index-btn"%>|
          <% if logged_in?%>
          <% if post.user_id == current_user.id%>
              <%= link_to 'Edit', edit_post_path(post),class:"btn btn-warning index-btn" %>|
              <%= link_to 'Destroy', post, class:"btn btn-danger index-btn",method: :delete, data: { confirm: 'Are you sure?' } %>
                <%end%>  
                <%end%> 
              </div>
            </div>    
          <% end %>
        </div>
    </div>
    <div class="col-6 left-card">
      <div class="card user-card">
        <h3>All Users</h3>
      <% @posts.each do |post| %>
        <div><%=post.user.name%></div>
      <%end%>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container new-post">
    <h1>Add Post</h1>
    <%= render 'form', post: @post %>
    <%= link_to 'Back', posts_path %>
</div>

app/views/posts/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  <div class="card show-card">
      <div class="card-body">
        <div><%= @post.blog %></div>
        <br>
        <div>
        <%if @post.image.present? %>
          <%= image_tag @post.image.url, size:"150x150" %>
        <%else%>
        <%end%>
        </div>
        Posted By: <%= @post.user.name %>
      </div>    
    <div class="card-footer">
      <%if logged_in? %>
      <% unless @post.user_id == current_user.id %>
      <% if @favorite.present? %>
        <%= link_to 'Cancel favorite', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
      <% else %>
        <%= link_to 'Make it a favorite', favorites_path(post_id: @post.id), method: :post, class: 'btn btn-primary' %>
      <% end %>
      <% end %>
      <%end%>

      <%= link_to 'Edit', edit_post_path(@post) %> |
      <%= link_to 'Back', posts_path %>
  </div>
    </div>

</div>